"""
Random Clifford circuit primitives and brickwork hybrid circuit for MIPT simulations.
"""

import numpy as np
from itertools import product as _iproduct
from .stabilizer import StabilizerState


def _pauli_action(gates):
    """Pauli-conjugation signature of an H/S gate sequence.

    Computes how the sequence C acts on single-qubit Paulis by conjugation:
        C X C^dag  and  C Z C^dag
    using the stabilizer tableau on a 1-qubit state.

    Returns ((phase_X, x_X, z_X), (phase_Z, x_Z, z_Z)) where:
        phase in {0=+, 1=-}
        (x_bit, z_bit) in {(1,0)=X, (0,1)=Z, (1,1)=Y}

    Used at import time to verify that SINGLE_QUBIT_CLIFFORDS covers all
    24 distinct single-qubit Clifford actions without duplicates.
    """

    def _apply_and_read(prep_h):
        s = StabilizerState(1)
        if prep_h:
            s.apply_h(0)  # stabilizer: Z -> X
        for g in gates:
            if g == "H":
                s.apply_h(0)
            else:
                s.apply_s(0)
        row = s.tab[1]  # stabilizer row (row index n=1 for a 1-qubit state)
        return (int(row[2]), int(row[0]), int(row[1]))  # (phase, x_bit, z_bit)

    return (_apply_and_read(True), _apply_and_read(False))  # (C X C†, C Z C†)


def _build_single_qubit_cliffords():
    """Generate all 24 single-qubit Clifford elements as H/S sequences.

    Enumerates every H/S sequence of length 0..6, computes each sequence's
    Pauli action on X and Z via the stabilizer tableau, and keeps the first
    (shortest) representative of each distinct action.  Asserts that exactly
    24 distinct actions are found.

    The single-qubit Clifford group has order 24 and is generated by H and S;
    all elements have shortest H/S representatives of length at most 6.
    """
    seen = {}
    for length in range(7):
        for seq in _iproduct(("H", "S"), repeat=length):
            sig = _pauli_action(seq)
            if sig not in seen:
                seen[sig] = seq

    result = list(seen.values())
    assert (
        len(result) == 24
    ), f"Expected 24 unique single-qubit Clifford actions, found {len(result)}"
    return result


SINGLE_QUBIT_CLIFFORDS = _build_single_qubit_cliffords()
assert len(SINGLE_QUBIT_CLIFFORDS) == 24


def apply_single_qubit_clifford(state: StabilizerState, qubit: int, gates: tuple):
    for g in gates:
        if g == "H":
            state.apply_h(qubit)
        else:
            state.apply_s(qubit)


def random_single_qubit_clifford(state: StabilizerState, qubit: int, rng=None):
    # Uniform over the verified 24-element single-qubit Clifford group.
    idx = int(rng.integers(24) if rng is not None else np.random.randint(24))
    apply_single_qubit_clifford(state, qubit, SINGLE_QUBIT_CLIFFORDS[idx])


def random_two_qubit_clifford(state: StabilizerState, q0: int, q1: int, rng=None):
    """Random 2-qubit Clifford via decomposition into 1Q Cliffords and CNOTs.

    Each 1Q gate is sampled uniformly from the verified 24-element single-qubit
    Clifford group (SINGLE_QUBIT_CLIFFORDS is programmatically enumerated and
    deduplicated by Pauli action at import time).

    The full 2-qubit gate ensemble is not verified as a uniform sampler over
    the 11520-element 2-qubit Clifford group; it is expected to produce
    scrambling Clifford dynamics appropriate for the MIPT universality class.
    """
    # TODO: Verify whether this decomposition is uniform over the full
    # 11520-element 2-qubit Clifford group (requires group-theoretic analysis
    # or exhaustive Haar-distance measurement).
    random_single_qubit_clifford(state, q0, rng)
    random_single_qubit_clifford(state, q1, rng)
    state.apply_cnot(q0, q1)
    random_single_qubit_clifford(state, q0, rng)
    random_single_qubit_clifford(state, q1, rng)
    state.apply_cnot(q1, q0)
    random_single_qubit_clifford(state, q0, rng)
    random_single_qubit_clifford(state, q1, rng)


def brickwork_layer(state: StabilizerState, layer_index: int, rng=None):
    """Brickwork pattern of random 2-qubit Cliffords.

    Even layers: pairs (0,1),(2,3),(4,5),...
    Odd  layers: pairs (1,2),(3,4),(5,6),...
    Boundary qubits that cannot be paired get a random single-qubit Clifford.
    """
    n = state.n
    start = layer_index % 2
    paired = set()
    for i in range(start, n - 1, 2):
        random_two_qubit_clifford(state, i, i + 1, rng)
        paired.add(i)
        paired.add(i + 1)
    for i in range(n):
        if i not in paired:
            random_single_qubit_clifford(state, i, rng)


def measurement_layer(state: StabilizerState, p: float, rng=None):
    """Measure each qubit independently with probability p. Outcomes are discarded."""
    mask = (rng.random(state.n) if rng is not None else np.random.rand(state.n)) < p
    for i in range(state.n):
        if mask[i]:
            state.measure(i, rng)


def run_circuit(
    n_qubits: int, p_meas: float, n_steps: int, warmup: int = None, rng=None
) -> StabilizerState:
    """Run hybrid random Clifford + measurement circuit to steady state.

    Warmup uses the same p_meas rate as the main run -- essential for reaching
    the correct steady state of the hybrid Markov chain at rate p_meas.

    Args:
        n_qubits: system size
        p_meas:   single-site measurement probability per layer (0 to 1)
        n_steps:  brickwork + measurement cycles after warmup
        warmup:   thermalization cycles (default 3 * n_qubits)
        rng:      numpy.random.Generator for reproducible runs; uses global
                  numpy RNG when None (backward-compatible default).
    Returns:
        StabilizerState in steady state at rate p_meas.
    """
    if warmup is None:
        warmup = 3 * n_qubits

    state = StabilizerState(n_qubits)

    for t in range(warmup):
        brickwork_layer(state, t, rng)
        measurement_layer(state, p_meas, rng)

    for t in range(n_steps):
        brickwork_layer(state, warmup + t, rng)
        measurement_layer(state, p_meas, rng)

    return state
